---
# Ansible Playbook to upgrade Cisco IOS 
- name: Upgrade CISCO IOS 
  hosts: asa_firewall
  
  gather_facts: true
  connection: network_cli

  vars:
    ansible_network_os: ios
  tasks:
      ## Create backup folder for today 
 
- hosts: localhost
 
  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"
 
   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"
 
   - name: Create Directory {{hostvars.localhost.DTG}}
     file:
      path: /etc/ansible/accel/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true

  ## Backup Running Config 
 
- hosts: asa_firewall
  connection: network_cli
  vars:
    ansible_network_os: ios
  gather_facts: true
 
  tasks:
   - name: Backup Running Config  
     asa_command:
       commands: show run  
     register: config
 
   - name: Save output to accel backup
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/root/asa_backup/{{hostvars.localhost.DTG}}/{{ inventory_net_hostname }}backup-config.txt"

   - name: Save running config 
     ios_config:
      save_when: always 
      ## Copy software to target device 
